### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by titanShubh** [zenitsu0509/ARYA_Chatbot#3]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://aryachatbot.streamlit.app/zenitsu0509/arya_chatbot/main/streamlit.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by zenitsu0509** [comment]
your problem is sovled now you can try it.
